name: CI / Lint / Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  ci:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [lts/*]

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      # Install dependencies (safe without package-lock.json)
      - name: Install dependencies
        run: npm install

      # Run ESLint (warnings/errors will not fail the workflow)
      - name: Run linter
        run: npx eslint . --ext .js || true

      # Run tests (workflow won’t fail if no tests yet)
      - name: Run tests
        run: |
          if [ -f package.json ]; then
            npm test || true
          fi
